/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author ACER
 */
public class DanhMuc extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public DanhMuc() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(1300, 730);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblLogo = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        cboTenLoai = new javax.swing.JComboBox<>();
        cboMaLoai = new javax.swing.JComboBox<>();
        btnMoi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnTrangChu1 = new javax.swing.JButton();
        btnHoaDon1 = new javax.swing.JButton();
        btnChiTietHD1 = new javax.swing.JButton();
        btnNhanVien1 = new javax.swing.JButton();
        btnDanhMuc1 = new javax.swing.JButton();
        btnMonAn1 = new javax.swing.JButton();
        btnDoanhThu1 = new javax.swing.JButton();
        btnKhuyenMai1 = new javax.swing.JButton();
        btnTaiKhoan2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(231, 219, 208));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(68, 7, 7));
        jLabel1.setText("DANH   MỤC   MÓN   ĂN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mã loại : ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tên loại :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã món ", "Tên món", "Hình ảnh"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblLogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Them.png"))); // NOI18N
        btnThem.setText("Thêm");

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Xoa.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Moi.png"))); // NOI18N
        btnSua.setText("Sửa");

        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new.png"))); // NOI18N
        btnMoi.setText("Mới");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboMaLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMoi)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(381, 381, 381))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cboMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cboTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(56, Short.MAX_VALUE))))
        );

        jPanel3.setBackground(new java.awt.Color(81, 5, 5));

        btnTrangChu1.setBackground(new java.awt.Color(95, 5, 11));
        btnTrangChu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTrangChu1.setForeground(new java.awt.Color(255, 255, 255));
        btnTrangChu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        btnTrangChu1.setText("Trang chủ");
        btnTrangChu1.setBorder(null);
        btnTrangChu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChu1ActionPerformed(evt);
            }
        });

        btnHoaDon1.setBackground(new java.awt.Color(95, 5, 11));
        btnHoaDon1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHoaDon1.setForeground(new java.awt.Color(255, 255, 255));
        btnHoaDon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bill.png"))); // NOI18N
        btnHoaDon1.setText("Hóa đơn");
        btnHoaDon1.setBorder(null);
        btnHoaDon1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHoaDon1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHoaDon1.setIconTextGap(20);

        btnChiTietHD1.setBackground(new java.awt.Color(95, 5, 11));
        btnChiTietHD1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTietHD1.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTietHD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ChiTietBill.png"))); // NOI18N
        btnChiTietHD1.setText("Chi tiết hóa đơn");
        btnChiTietHD1.setBorder(null);
        btnChiTietHD1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnChiTietHD1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnChiTietHD1.setIconTextGap(20);
        btnChiTietHD1.setMargin(new java.awt.Insets(10, 14, 2, 14));

        btnNhanVien1.setBackground(new java.awt.Color(95, 5, 11));
        btnNhanVien1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNhanVien1.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/staff.png"))); // NOI18N
        btnNhanVien1.setText("Nhân viên");
        btnNhanVien1.setBorder(null);
        btnNhanVien1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhanVien1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNhanVien1.setIconTextGap(20);
        btnNhanVien1.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnNhanVien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVien1ActionPerformed(evt);
            }
        });

        btnDanhMuc1.setBackground(new java.awt.Color(95, 5, 11));
        btnDanhMuc1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDanhMuc1.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhMuc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DanhMuc.png"))); // NOI18N
        btnDanhMuc1.setText("Danh mục");
        btnDanhMuc1.setBorder(null);
        btnDanhMuc1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDanhMuc1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDanhMuc1.setIconTextGap(20);
        btnDanhMuc1.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnDanhMuc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhMuc1ActionPerformed(evt);
            }
        });

        btnMonAn1.setBackground(new java.awt.Color(95, 5, 11));
        btnMonAn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMonAn1.setForeground(new java.awt.Color(255, 255, 255));
        btnMonAn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/monAn.png"))); // NOI18N
        btnMonAn1.setText("Món ăn");
        btnMonAn1.setBorder(null);
        btnMonAn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMonAn1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMonAn1.setIconTextGap(20);
        btnMonAn1.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnMonAn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonAn1ActionPerformed(evt);
            }
        });

        btnDoanhThu1.setBackground(new java.awt.Color(95, 5, 11));
        btnDoanhThu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDoanhThu1.setForeground(new java.awt.Color(255, 255, 255));
        btnDoanhThu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DoanhThu.png"))); // NOI18N
        btnDoanhThu1.setText("Doanh thu");
        btnDoanhThu1.setBorder(null);
        btnDoanhThu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDoanhThu1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDoanhThu1.setIconTextGap(20);
        btnDoanhThu1.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnDoanhThu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoanhThu1ActionPerformed(evt);
            }
        });

        btnKhuyenMai1.setBackground(new java.awt.Color(95, 5, 11));
        btnKhuyenMai1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKhuyenMai1.setForeground(new java.awt.Color(255, 255, 255));
        btnKhuyenMai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/KhuyenMai.png"))); // NOI18N
        btnKhuyenMai1.setText("Khuyến mãi");
        btnKhuyenMai1.setBorder(null);
        btnKhuyenMai1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKhuyenMai1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnKhuyenMai1.setIconTextGap(20);
        btnKhuyenMai1.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnKhuyenMai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhuyenMai1ActionPerformed(evt);
            }
        });

        btnTaiKhoan2.setBackground(new java.awt.Color(95, 5, 11));
        btnTaiKhoan2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTaiKhoan2.setForeground(new java.awt.Color(255, 255, 255));
        btnTaiKhoan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Acount.png"))); // NOI18N
        btnTaiKhoan2.setText("Tài Khoản");
        btnTaiKhoan2.setBorder(null);
        btnTaiKhoan2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTaiKhoan2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnTaiKhoan2.setIconTextGap(20);
        btnTaiKhoan2.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnTaiKhoan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoan2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnChiTietHD1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
            .addComponent(btnMonAn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNhanVien1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnKhuyenMai1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTrangChu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDoanhThu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDanhMuc1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHoaDon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTaiKhoan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnTrangChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTaiKhoan2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChiTietHD1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDanhMuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMonAn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDoanhThu1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKhuyenMai1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTrangChu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrangChu1ActionPerformed

    private void btnNhanVien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVien1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhanVien1ActionPerformed

    private void btnDanhMuc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhMuc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDanhMuc1ActionPerformed

    private void btnMonAn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonAn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMonAn1ActionPerformed

    private void btnDoanhThu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoanhThu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoanhThu1ActionPerformed

    private void btnKhuyenMai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhuyenMai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKhuyenMai1ActionPerformed

    private void btnTaiKhoan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaiKhoan2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhMuc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTietHD;
    private javax.swing.JButton btnChiTietHD1;
    private javax.swing.JButton btnDanhMuc;
    private javax.swing.JButton btnDanhMuc1;
    private javax.swing.JButton btnDoanhThu;
    private javax.swing.JButton btnDoanhThu1;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnHoaDon1;
    private javax.swing.JButton btnKhuyenMai;
    private javax.swing.JButton btnKhuyenMai1;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnMonAn;
    private javax.swing.JButton btnMonAn1;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnNhanVien1;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTaiKhoan1;
    private javax.swing.JButton btnTaiKhoan2;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnTrangChu1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaLoai;
    private javax.swing.JComboBox<String> cboTenLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
